// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import frc.robot.Constants;
import frc.robot.commands.*;
import frc.robot.math.Vector2;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.motorcontrol.MotorController;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.TalonFX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class TelescopingArm extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Defining TalonFX motor classes
    public static TalonFX pivotMotor1;
    public static TalonFX pivotMotor2;
    public static TalonFX telescopingWristMotor;
    public static TalonFX telescopingMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
    *
    */
    public TelescopingArm() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // Defining TalonFX id's
        pivotMotor1 = new TalonFX(8);
        pivotMotor1.setInverted(false);

        pivotMotor2 = new TalonFX(9);
        pivotMotor2.setInverted(false);

        telescopingWristMotor = new TalonFX(10);
        telescopingWristMotor.setInverted(false);

        telescopingMotor = new TalonFX(11);
        telescopingMotor.setInverted(false);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
        // PivotMotor moves to set position to move Telescoping Arm
    public void goToPos(Vector2 pos) {
        pivotMotor1.set(ControlMode.Position, Constants.armZero + pos.angle() * (1024 / Math.PI));
        pivotMotor2.set(ControlMode.Follower, 9);

        telescopingMotor.set(ControlMode.Position, Constants.armZero + pos.magnitude() * Constants.armLenghtToUnits);
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}
